env:
  browser: true
  es2021: true
  node: true
  jest/globals: true
extends:
  - 'plugin:vue/essential'
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
  - jest
rules:
  import/no-unresolved: off
  import/extensions: off
  camelcase: off
